### ISSUE TITLE
Error when clicking "Mark as read" in customer front end

### ISSUE THREAD

**Issue by phil0135** [reneeb/otrs-ProductNews#12]
Hello, 

thanks for the very useful addon. I just found a problem displaying messages in the customer frontend. 
If a user clicks "Mark as read" a JavaScript Error Popup is displayed and the following error can be found in the log file.
`Module Kernel::Modules::AgentProductNewsMarkRead not registered in Kernel/Config.pm`

I think it can be fixed by adding the module AgentProductNewsMarkRead in Kernel/Config/Files/ProductNews.xml.

```
 <ConfigItem Name="CustomerFrontend::Module###AgentProductNewsMarkRead" Required="0" Valid="1">
        <Description Translatable="1">Frontend module registration for the agent interface.</Description>
        <Group>ProductNews</Group>
        <SubGroup>Frontend::Customer::ModuleRegistration</SubGroup>
        <Setting>
            <FrontendModuleReg>
                <Description Translatable="1">Product News</Description>
                <NavBarName></NavBarName>
                <Title Translatable="1">Product News</Title>
            </FrontendModuleReg>
        </Setting>
    </ConfigItem>
```

Best regards, 

Philipp

**Comment by reneeb** [comment]
Thanks for your bugreport!

The issue should be fixed in the latest version that will appear on OPAR in a few minutes.

Kind regards,
Renée
