### ISSUE TITLE
Change title of dashboard element

### ISSUE THREAD

**Issue by reneeb** [reneeb/otrs-ProductNews#5]
There's already a built-in dashboard element named "Product News". Change the title to "Advanced Product News" or something like that...

**Comment by urbalazs** [comment]
Hi @reneeb 
This is the same issue, that I mentioned in https://github.com/reneeb/otrs-ProductNews/pull/9.
Can you rename "Product news" to "Own Product News"?

**Comment by reneeb** [comment]
Fixed in 5.0.5
